[workspace]
members = ["core", "gtk", "gui", "mod-pod2", "mod-pocket", "mod-xt", "mod-x3"]

[workspace.package]
version = "0.0.0"
authors = ["Artem Egorkine <arteme@gmail.com>"]
edition = "2021"
rust-version = "1.65"
