[package]
name = "pod-gui"
version = "0.1.0"
authors = ["Artem Egorkine <arteme@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
glib = "0.14.8"
gdk = "0.14.3"
gtk = { version = "0.14.3" } # gtk 3.18
clap = { version = "3.0.6", features = ["derive"] }
simple_logger = "1.6.0"
multimap = "0.8.3"

pin-project = "=0.4.29" # needed to get glib dep to comile :(

log = "*" # defined in pod-core
tokio = "*" # defined in pod-core
anyhow = "*" # defined in pod-code

pod-core = { path = "../core" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[[bin]]
name = "pod-gui"
