[package]
name = "pod-cli"
version = "0.1.0"
authors = ["Artem Egorkine <arteme@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
log = "0.4.8"
simple_logger = "1.6.0"
anyhow = "1.0.31"
pod-core = { path = "../core" }

[[bin]]
name = "pod-cli"
path = "src/main.rs"
