[package]
name = "pod-core"
version = "0.1.0"
authors = ["Artem Egorkine <arteme@gmail.com>"]
edition = "2018"

[dependencies]
midir = "0.6.0"
serde = { version = "1.0.110", features = ["derive"] }
log = "0.4.8"
anyhow = "1.0.31"
arrayref = "0.3.6"
lazy_static = "1.4.0"
