[package]
name = "pod-gtk"
version = "0.3.0-dev"
authors = ["Artem Egorkine <arteme@gmail.com>"]
edition = "2018"

[dependencies]
glib = "0.14.8"
gdk = "0.14.3"
gtk = { version = "0.14.3" } # gtk 3.18
multimap = "=0.8.3"

pin-project = "=0.4.29" # needed to get glib dep to comile :(

log = "*" # defined in pod-core
tokio = "*" # defined in pod-core
anyhow = "*" # defined in pod-code

pod-core = { path = "../core" }
